name: GitHub CI

on: [push, pull_request]

jobs:
  npm:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-18.04]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install with npm
        run: |
          npm install
      - name: Build
        run: |
          npm run build && npm run build-storybook
      - name: Run tests
        run: |
          npm run test
  yarn:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-18.04]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install with yarn
        run: |
          curl -o- -L https://yarnpkg.com/install.sh | bash
          yarn install
      - name: Build
        run: |
          yarn build && yarn build-storybook
      - name: Run tests
        run: |
          yarn test
